### ISSUE TITLE
How to custom font-face src path ?

### ISSUE THREAD

**Issue by lc-soft** [jeerbl/webfonts-loader#26]
My directory structure:

```
myapp/
   app/
      assets/
         javascripts/
          octicons.font.js
          ...
        stylesheets/
  static/
    javascripts/
    stylesheets/
    fonts/
  node_modules/
      
```

`octicons.font.js` file content:

``` js
module.exports = {
  files: [
    '../../../node_modules/octicons/build/svg/*.svg'
  ],
  fontName: 'octicons',
  classPrefix: 'octicon-',
  baseSelector: '.octicon',
  types: ['eot', 'woff', 'woff2', 'ttf', 'svg'],
  fileName: '../fonts/[fontname].[ext]'
};
```

This configuration can successfully output font files and css, But the output css is not what I want:

``` css
@font-face {
  font-family: "octicons";
  src: url("/fonts/octicons.eot?#iefix") format("embedded-opentype"),
  url("/fonts/octicons.woff") format("woff"),
  url("/fonts/octicons.woff2") format("woff2"),
  url("/fonts/octicons.ttf") format("truetype"),
  url("/fonts/octicons.svg#octicons") format("svg");
}
```

I want src path in the `/static/fonts/` directory, **How to configure it?**

I have tried this:

``` js
module.exports = {
  files: [
    '../../../node_modules/octicons/build/svg/*.svg'
  ],
  dest: '../../../static/fonts',
  fontName: 'octicons',
  classPrefix: 'octicon-',
  baseSelector: '.octicon',
  types: ['eot', 'woff', 'woff2', 'ttf', 'svg'],
  fileName: '[fontname].[ext]'
};
```

But there are some errors, **why is it going to parse the font file?**

```
ERROR in F:/repos/myapp/static/fonts/octicons.eot
    Module parse failed: F:\repos\myapp\static\fonts\octicons.eot Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ F:/repos/myapp/node_modules/_css-loader@0.28.4@css-loader!F:/repos/myapp/node_modules/_webfonts-loader@2.0.2@webfonts-loader!./octicons.font.js 6:85-130
```
